version: '3'
services:
  app:
    build: container
    ports:
        - "4040:3000"
    volumes:
        - src:/var/www/src/:Z
    tty: true
volumes:
  src:
    driver_opts: 
      type: none
      device: /Users/takanori/Desktop/Linebot/WeatherBot/src
      o: bind